name: Blackboard → Notion Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  dryrun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          python -V
          echo "DRY_RUN=${{ secrets.DRY_RUN }}"
      - name: Ejecutar sincronización
        if: ${{ secrets.DRY_RUN != 'true' }}
        run: python app/sync/sync_runner.py
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          BLACKBOARD_CLIENT_ID: ${{ secrets.BLACKBOARD_CLIENT_ID }}
          BLACKBOARD_CLIENT_SECRET: ${{ secrets.BLACKBOARD_CLIENT_SECRET }}
          BLACKBOARD_DOMAIN: ${{ secrets.BLACKBOARD_DOMAIN }}
